/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aaron_indoorpanorama_util_opencv_ImagePro */

#ifndef _Included_com_aaron_indoorpanorama_util_opencv_ImagePro
#define _Included_com_aaron_indoorpanorama_util_opencv_ImagePro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aaron_indoorpanorama_util_opencv_ImagePro
 * Method:    stitch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aaron_indoorpanorama_util_opencv_ImagePro_stitch
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
